const W=window.WORKOUTS,O=["seg","ter","qua","qui","sex"],$=s=>document.querySelector(s);let day=localStorage.getItem("activeDay")||"seg",timerId=null,timerInitial=0,timerLeft=0;
const DB={get weights(){return JSON.parse(localStorage.getItem("exerciseWeights")||"{}")},set weights(v){localStorage.setItem("exerciseWeights",JSON.stringify(v))},get history(){return JSON.parse(localStorage.getItem("weightHistory")||"[]")},set history(v){localStorage.setItem("weightHistory",JSON.stringify(v))}};
function fmt(s){return`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function nav(){tabs.innerHTML="";navEl.innerHTML="";O.forEach(k=>{let d=W[k],a=document.createElement("button");a.textContent=d.label;a.className=k===day?"active":"";a.onclick=()=>select(k);tabs.appendChild(a);let b=document.createElement("button");b.textContent=d.short;b.className=k===day?"active":"";b.onclick=()=>select(k);navEl.appendChild(b)})}
const tabs=$("#tabs"),navEl=$("#nav"),main=$("#main");
function lastWeight(id){return DB.weights[id]??""}
function deltaClass(oldV,newV){if(oldV===""||newV==="")return["same",""];let o=Number(oldV),n=Number(newV);if(n>o)return["up",`+${n-o} lb`];if(n<o)return["down",`${n-o} lb`];return["same","Mesma carga"]}
function page(){let d=W[day];document.documentElement.style.setProperty("--day",d.color);main.innerHTML=`<section class="hero"><h2>${d.label} • ${d.title}</h2><p>${d.focus}</p><button class="historyBtn" onclick="openHistory()">Histórico de cargas</button></section>${d.exercises.map((e,i)=>{let lw=lastWeight(e.id);return`<article class="card"><div class="cardTop"><div><h3>${i+1}. ${e.pt}</h3><div class="en">${e.en}</div></div><div class="last"><small>Última carga</small><strong>${lw!==""?lw+" lb":"—"}</strong></div></div><div class="pills"><div class="pill"><small>Foco</small><strong>${e.muscle}</strong></div><div class="pill"><small>Séries</small><strong>${e.sets}</strong></div><div class="pill"><small>Descanso</small><strong>${fmt(e.rest)}</strong></div></div><div class="label good">Como fazer</div><ul>${e.do.map(x=>`<li>${x}</li>`).join("")}</ul><div class="label bad">Evite</div><ul>${e.avoid.map(x=>`<li>${x}</li>`).join("")}</ul><div class="weightBox"><div class="weightRow"><div class="weightField"><label>Carga de trabalho (lb)</label><input id="w-${e.id}" inputmode="decimal" value="${lw}" placeholder="Ex.: 45" oninput="previewDelta('${e.id}',this.value)"></div><button class="saveBtn" onclick="saveWeight('${e.id}','${e.pt.replaceAll("'","\'")}')">Salvar</button></div><div id="d-${e.id}" class="delta same">${lw!==""?"Pronto para repetir ou aumentar.":"Nenhuma carga salva ainda."}</div></div><button class="timerBtn" onclick="startTimer(${e.rest},'${e.pt.replaceAll("'","\'")}')">Descanso ${fmt(e.rest)}</button></article>`}).join("")}`;scrollTo({top:0,behavior:"instant"})}
function select(k){day=k;localStorage.setItem("activeDay",k);nav();page()}window.select=select;
function previewDelta(id,v){let [c,t]=deltaClass(lastWeight(id),v);let el=$("#d-"+id);el.className="delta "+c;el.textContent=t||"Digite a carga usada."}window.previewDelta=previewDelta;
function saveWeight(id,name){let input=$("#w-"+id),raw=input.value.trim().replace(",",".");if(raw===""){alert("Digite a carga em lb.");return}let n=Number(raw);if(!Number.isFinite(n)||n<0||n>1500){alert("Digite uma carga válida.");return}let old=lastWeight(id),w=DB.weights;w[id]=n;DB.weights=w;let h=DB.history;h.unshift({id,name,weight:n,previous:old,date:new Date().toISOString()});DB.history=h.slice(0,500);let [c,t]=deltaClass(old,n);let el=$("#d-"+id);el.className="delta "+c;el.textContent=t||"Carga salva.";let card=input.closest(".card");card.querySelector(".last strong").textContent=n+" lb"}window.saveWeight=saveWeight;
function openHistory(){let h=DB.history;$("#historyBody").innerHTML=h.length?h.slice(0,80).map(x=>`<div class="histItem"><h4>${x.name} • ${x.weight} lb</h4><p>${new Date(x.date).toLocaleDateString("pt-BR")} ${x.previous!==""?`• anterior: ${x.previous} lb`:""}</p></div>`).join(""):`<div class="histItem"><p>Nenhuma carga salva ainda.</p></div>`;$("#historyModal").classList.add("show")}window.openHistory=openHistory;$("#closeHistory").onclick=()=>$("#historyModal").classList.remove("show");
function startTimer(s,l){clearInterval(timerId);timerInitial=timerLeft=s;$("#timerLabel").textContent=l;$("#timerModal").classList.add("show");updateTimer();timerId=setInterval(()=>{timerLeft--;updateTimer();if(timerLeft<=0){clearInterval(timerId);if(navigator.vibrate)navigator.vibrate([200,100,200])}},1000)}window.startTimer=startTimer;
function updateTimer(){$("#timerText").textContent=fmt(Math.max(0,timerLeft))}
$("#closeTimer").onclick=()=>{clearInterval(timerId);$("#timerModal").classList.remove("show")};$("#restartTimer").onclick=()=>startTimer(timerInitial,$("#timerLabel").textContent);
if(localStorage.getItem("theme")==="light")document.documentElement.classList.add("light");$("#theme").textContent=document.documentElement.classList.contains("light")?"🌙":"☀️";$("#theme").onclick=()=>{document.documentElement.classList.toggle("light");localStorage.setItem("theme",document.documentElement.classList.contains("light")?"light":"dark");$("#theme").textContent=document.documentElement.classList.contains("light")?"🌙":"☀️"};
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));nav();page();